---
- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags: metallb

- name: Deploy 1password-credentials.json secret
  include_tasks: op-credentials.yml
  when: "install_onepassword_secret | bool"

# - name: Deploy sops-age secret
#   include_tasks: sops-age.yaml

- name: Apply longhorn storage node labels
  include_tasks: storage.yml

- name: Grab new kubeconfig
  include_tasks: kubeconfig.yaml

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
