---

- name: Copy sops encryption keyfile to first master
  template:
    src: "sops-age-secret.j2"
    dest: "/tmp/k3s/sops-age-secret.yaml"
    owner: "{{ ansible_user_id }}"
    mode: 0700
  with_items: "{{ groups['master'] }}"
  run_once: true

- name: Create sops-age secret
  command: >-
    k3s kubectl apply -f /tmp/k3s/sops-age-secret.yaml
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5
