---
# Label the nodes to ensure Longhorn volumes are only placed on disks of the storage nodes:
# https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/#tell-longhorn-to-create-a-default-disk-on-a-specific-set-of-nodes
- name: Apply label "node.longhorn.io/create-default-disk=true" on storage nodes in Kubernetes
  become: yes
  command: k3s kubectl label nodes --overwrite {{ item }} node.longhorn.io/create-default-disk=true
  loop: "{{ hostvars[inventory_hostname]['groups']['longhorn_storage'] }}"
  run_once: true
